import { Conteudo } from './interface';
//ficheiro com dados iniciais 
//filmes e séries para adicionar e testar 
export const DADOS_INICIAIS: Conteudo[] = [
    {id: new Date(), 
        titulo: 'Conclave',
        tipo: 'filme', 
        estado: 'visto',
        avaliacao: 7,
        genero: 'suspense',
        criador: 'Edward Berger',
        anoLancamento: 2024, 
        criadoEm: new Date(),
    },
    {id: new Date(),
        titulo: 'Challengers',
        tipo: 'filme',
        estado: 'visto',
        avaliacao: 6.5,
        genero: 'comédia',
        criador: 'Luca Guadagnino',
        anoLancamento: 2024,
        criadoEm: new Date(),
    },
    {id: new Date(),
        titulo: 'From',
        tipo: 'serie',
        estado: 'visto',
        avaliacao: 8,
        genero: 'drama',
        criador: 'John Griffin',
        anoLancamento: 2022,
        criadoEm: new Date(),
    },
    {id: new Date(),
        titulo: 'Pluribus',
        tipo: 'serie',
        estado: 'visto',
        avaliacao: 8,
        genero: 'comédia',
        criador: 'Jonny Gomez',
        anoLancamento: 2025,
        criadoEm: new Date(),
    }
]